routes/web.php
<?php
use App\Http\Middleware\CheckUser;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware(CheckUser::class);

Route::get('login',[
    'as'=>'home.login',
    'uses'=>'HomeController@login'
]);


Route::get('register',[
    'as'=>'home.register',
    'uses'=>'HomeController@register'
]);

Route::post('singin',[
    'as'=>'home.singin',
    'uses'=>'HomeController@singin'
]);

Route::post('singup',[
    'as'=>'home.singup',
    'uses'=>'HomeController@singup'
]);

Route::get('logout',[
    'as'=>'home.logout',
    'uses'=>'Auth\LoginController@logout'
]);

Route::get('admin/customers',[
    'as'=>'admin.customers',
    'uses'=>'AdminController@customers'
]);

Route::get('admin/visits',[
    'as'=>'admin.visits',
    'uses'=>'AdminController@visits'
]);

Route::get('admin/reports/cities',[
    'as'=>'admin.reports.cities',
    'uses'=>'AdminController@reportsCities'
]);

Route::get('admin/reports/customers/{id?}',[
    'as'=>'admin.reports.customers',
    'uses'=>'AdminController@reportsCustomers'
]);

Route::get('admin/sellers',[
    'as'=>'admin.sellers',
    'uses'=>'AdminController@sellers'
]);
Route::get('cities_departaments/{id?}',[
    'as'=>'cities.departament',
    'uses'=>'CitiesController@citiesDepartamentId'
]);
Route::get('departaments_city/{id?}',[
    'as'=>'departaments.city',
    'uses'=>'DepartamentsController@departamentByCity'
]);
Route::resource('customers','CustomersController');
Route::resource('countries','CountriesController');
Route::resource('departaments','DepartamentsController');
Route::resource('city','CitiesController');
Route::resource('visits','VisitsController');
Route::resource('sellers','SellersController');

resources/views/admin/customers.blade.php
@extends('layout.layout')
@section('content')
    <h1>Clientes</h1>
    <div class="row">
        <div class="col-12 text-right">
            <button class="btn pull-right btn-primary"  data-toggle="modal" data-target="#modal_customer"><i class="material-icons">Agregar</i></button>
        </div>
    </div>

    @if(count($customers)>0)
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Nombre</th>
                    <th>Dirección</th>
                    <th>Telefono</th>
                    <th>cupo</th>
                    <th>Saldo cupo</th>
                    <th>Porcentaje cup</th>
                    <th class="text-center">Geo</th>
                    <th class="text-center" colspan="3">Acción</th>
                </tr>
            </thead>
            <tbody class="body-customer" data-url="{!! route('customers.index') !!}" data-delete="{!! route('customers.destroy',null) !!}" data-show="{!! route('customers.show',null) !!}">
                @foreach($customers as $customer)
                    <tr>
                        <td>{!! $customer->id !!}</td>
                        <td>{!! $customer->name !!}</td>
                        <td>{!! $customer->address !!}</td>
                        <td>{!! $customer->phone !!}</td>
                        <td>{!! $customer->quota !!}</td>
                        <td>{!! $customer->balance_quota !!}</td>
                        <td>{!! $customer->percentage_visits !!}</td>
                        <td>{!! $customer->city->name !!}-{!! $customer->city->departament->name !!}</td>
                        <td><a href="{!! route('admin.reports.customers',$customer->id) !!}" data-id="{!! $customer->id !!}" class="btn btn-primary visit">Reporte</a></td>
                        <td><button data-id="{!! $customer->id !!}" class="btn btn-primary visit">Visita</button></td>
                        <td><button data-id="{!! $customer->id !!}" class="btn btn-primary edit">Editar</button></td>
                        <td><button data-id="{!! $customer->id !!}" class="btn btn-danger delete">Eliminar</button></td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <div class="row">
            <div class="col-12">
               {!!  $customers->render(); !!}
            </div>
        </div>
    @else
        <h2>No existe clientes</h2>
    @endif
    @include('admin.modals.customer')
    @include('admin.modals.visit')
@endsection
@section('scripts')
    {!! Html::script('js/admin.js') !!}
    {!! Html::script('js/customers.js'); !!}
    {!! Html::script('js/visits.js'); !!}
@endsection

resources/views/admin/reports.blade.php
@extends('layout.layout')
@section('content')
    <h1>Reportes</h1>
    <div id="stocks-div"></div>
    {!! $lava->render('BarChart', 'Votes', 'stocks-div') !!}
@endsection
@section('scripts')
    {!! Html::script('js/admin.js') !!}
@endsection

resources/views/admin/sellers.blade.php
@extends('layout.layout')
@section('content')
    <h1>Vendedores</h1>
    <div class="row">
        <div class="col-12 text-right">
            <button class="btn pull-right btn-primary"  data-toggle="modal" data-target="#modal_seller"><i class="material-icons">Agregar</i></button>
        </div>
    </div>

    @if(count($sellers)>0)
        <table class="table table-bordered table-responsive">
            <thead>
            <tr>
                <th>id</th>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Telefono</th>
                <th>Tipo de documento</th>
                <th>Numero de tarjeta</th>
                <th class="text-center" colspan="2">Action</th>
            </tr>
            </thead>
            <tbody class="body-seller" data-url="{!! route('sellers.index') !!}" data-delete="{!! route('sellers.destroy',null) !!}"
                   data-show="{!! route('sellers.show',null) !!}">
            @foreach($sellers as $seller)
                <tr>
                    <td>{!! $seller->id !!}</td>
                    <td>{!! $seller->name !!}</td>
                    <td>{!! $seller->address !!}</td>
                    <td>{!! $seller->phone_number !!}</td>
                    <td>{!! $seller->type_card !!}</td>
                    <td>{!! $seller->number_card !!}</td>
                    <td><button data-id="{!! $seller->id !!}" class="btn btn-primary edit">Editar</button></td>
                    <td><button data-id="{!! $seller->id !!}" class="btn btn-danger delete">Eliminar</button></td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="row">
            <div class="col-12">
                {!!  $sellers->render(); !!}
            </div>
        </div>
    @else
        <h2>No existe vendedores.</h2>
    @endif
    @include('admin.modals.seller')
@endsection
@section('scripts')
    {!! Html::script('js/admin.js') !!}
    {!! Html::script('js/sellers.js') !!}
@endsection

resources/views/admin/visits.blade.php
@extends('layout.layout')
@section('content')
    <h1>Visitas</h1>
    <div class="row">
        <div class="col-12 text-right">
            <button class="btn pull-right btn-primary"  data-toggle="modal" data-target="#modal_visit"><i class="material-icons">Agregar</i></button>
        </div>
    </div>

    @if(count($visits)>0)
        <table class="table table-bordered table-responsive">
            <thead>
            <tr>
                <th>id</th>
                <th>Cliente</th>
                <th>Vendedor</th>
                <th>Valor neto</th>
                <th>Fecha</th>
                <th>Valor visita</th>
            </tr>
            </thead>
            <tbody class="body-customer" data-url="{!! route('customers.index') !!}" data-delete="{!! route('customers.destroy',null) !!}" data-show="{!! route('customers.show',null) !!}">
            @foreach($visits as $visit)
                <tr>
                    <td>{!! $visit->id !!}</td>
                    <td>{!! $visit->customer->name !!}</td>
                    <td>{!! $visit->seller->name !!}</td>
                    <td>{!! $visit->value_neto !!}</td>
                    <td>{!! $visit->date !!}</td>
                    <td>{!! $visit->value_visits !!}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="row">
            <div class="col-12">
                {!!  $visits->render(); !!}
            </div>
        </div>
    @else
        <h2>No existe visitas.</h2>
    @endif

    @include('admin.modals.visit')
@endsection
@section('scripts')
    {!! Html::script('js/visits.js') !!}
    {!! Html::script('js/admin.js') !!}
@endsection