routes/web.php
<?php
use App\Http\Middleware\CheckUser;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware(CheckUser::class);

Route::get('login',[
    'as'=>'home.login',
    'uses'=>'HomeController@login'
]);


Route::get('register',[
    'as'=>'home.register',
    'uses'=>'HomeController@register'
]);

Route::post('singin',[
    'as'=>'home.singin',
    'uses'=>'HomeController@singin'
]);

Route::post('singup',[
    'as'=>'home.singup',
    'uses'=>'HomeController@singup'
]);

Route::get('logout',[
    'as'=>'home.logout',
    'uses'=>'Auth\LoginController@logout'
]);

Route::get('admin/customers',[
    'as'=>'admin.customers',
    'uses'=>'AdminController@customers'
]);

Route::get('admin/visits',[
    'as'=>'admin.visits',
    'uses'=>'AdminController@visits'
]);

Route::get('admin/reports/cities',[
    'as'=>'admin.reports.cities',
    'uses'=>'AdminController@reportsCities'
]);

Route::get('admin/reports/customers/{id?}',[
    'as'=>'admin.reports.customers',
    'uses'=>'AdminController@reportsCustomers'
]);

Route::get('admin/sellers',[
    'as'=>'admin.sellers',
    'uses'=>'AdminController@sellers'
]);
Route::get('cities_departaments/{id?}',[
    'as'=>'cities.departament',
    'uses'=>'CitiesController@citiesDepartamentId'
]);
Route::get('departaments_city/{id?}',[
    'as'=>'departaments.city',
    'uses'=>'DepartamentsController@departamentByCity'
]);
Route::resource('customers','CustomersController');
Route::resource('countries','CountriesController');
Route::resource('departaments','DepartamentsController');
Route::resource('city','CitiesController');
Route::resource('visits','VisitsController');
Route::resource('sellers','SellersController');

resources/views/admin/modals/customer.blade.php
<!-- Modal -->
<div class="modal fade" id="modal_customer" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cliente</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {!! Form::open(['url'=>route('customers.store'),'method'=>'post','class'=>'form_customer','id'=>'form_customer',
                'data-update'=>route('customers.update',null),'data-store'=>route('customers.store'),'data-id'=>'']) !!}

                <div class='form-group'>
                    <label for='name'>Nombre</label>
                    <input class='form-control' type='text' name='name' id='name'/>
                </div>

                <div class='form-group nit_field'>
                    <label for='nit'>Nit</label>
                    <input class='form-control' type='text' name='nit' id='nit'/>

                </div>
                <div class='form-group'>
                    <label for='address'>Direccion</label>
                    <input class='form-control' type='text' name='address' id='address'/>

                </div>

                <div class='form-group'>
                    <label for='phone'>Telefono</label>
                    <input class='form-control' type='text' name='phone' id='phone'/>
                </div>

                <div class='form-group'>
                    <label for='quota'>Cuota</label>
                    <input class='form-control' type='text' name='quota' id='quota'/>
                </div>
                <div class='form-group'>
                    <label for='balance_quota'>Saldo cuota</label>
                    <input class='form-control' type='text' name='balance_quota' id='balance_quota'/>

                </div>
                <div class='form-group'>
                    <label for='percentage_visits' class="d-block">Porcentaje</label>
                   {{-- <input class='form-control' type='text' name='percentage_visits' id='percentage_visits'/>--}}
                    <div class="col-10 sliderContainer d-inline" style="width: 100%">
                        <input class="form-control" name="percentage_visits" type="text" />
                    </div>
                    <div class="col-2 d-inline">
                        <span class="percentageValue">5%</span>
                    </div>

                </div>
                <div class='form-group'>
                    <label for='country'>Pais</label>
                    {!! Form::select('country',[''=>'Selected..']+$countries,null,['class'=>'form-control','id'=>'country',
                    'data-url'=>route('departaments.city'),'data-get'=>route('countries.index')]); !!}
                </div>
                <div class='form-group'>
                    <label for='departament'>Departamento</label>
                    {!! Form::select('departament',[''=>'Selected..'],null,['class'=>'form-control','disabled'=>'true',
                    'id'=>'departament','data-url'=>route('cities.departament'),'data-get'=>route('departaments.index')]); !!}
                </div>
                <div class='form-group'>
                    <label for='city'>Cuidad</label>
                    {!! Form::select('city_id',[''=>'Selected..'],null,['class'=>'form-control','disabled'=>'true',
                    'id'=>'city','data-url'=>'','data-get'=>route('city.index')]); !!}
                </div>

                <div class="modal-footer">

                    <button type="submit" class="btn btn-primary customer insert" id="submit_button">Guardar</button>
                </div>
                {!! Form::close() !!}
            </div>

        </div>
    </div>
</div>

resources/views/admin/modals/seller.blade.php
<!-- Modal -->
<div class="modal fade" id="modal_seller" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Vendedor</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {!! Form::open(['url'=>route('sellers.store'),'method'=>'post','class'=>'form_seller',
                'data-update'=>route('sellers.update',null),'data-store'=>route('sellers.store'),'data-id'=>'']) !!}
                <div class="form-group">
                    <label for="name">Nombre</label>
                    <input class="form-control" type="text" name="name" id="name">
                </div>
                <div class='form-group'>
                    <label for='email'>Email</label>
                    <input class='form-control' type='text' name='email' id='email'/>
                </div>
                <div class='form-group'>
                    <label for='address'>Direccion</label>
                    <input class='form-control' type='text' name='address' id='address'/>
                </div>
                <div class='form-group'>
                    <label for='type_card'>Tipo de tarjeta</label>
                    {!! Form::select('type_card',['cc'=>'C.C','ti'=>'T.I'],null,['class'=>'form-control','id'=>'type_card']); !!}
                </div>
                <div class='form-group'>
                    <label for='number_card'>Numero de tarjeta</label>
                    <input class='form-control' type='text' name='number_card' id='number_card'/>
                </div>
                <div class='form-group'>
                    <label for='phone_number'>Telefono</label>
                    <input class='form-control' type='text' name='phone_number' id='phone_number'/>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary seller insert" id="submit_button">Guardar</button>
                </div>
                {!! Form::close() !!}
            </div>

        </div>
    </div>
</div>

resources/views/admin/modals/visit.blade.php
<!-- Modal -->
<div class="modal fade" id="modal_visit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Visitas</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {!! Form::open(['url'=>route('visits.store'),'method'=>'post','class'=>'form_visit',
                'data-update'=>route('visits.update',null),'data-store'=>route('visits.store'),'data-id'=>'']) !!}
                <div class="form-group">
                    <label for="customer">Cliente</label>
                    <input class="form-control" type="text" name="customer" id="customer" data-id="" data-url="{!! route('customers.index') !!}">
                </div>
                <div class='form-group'>
                    <label for='name'>Vendedor</label>
                    <input class='form-control' type='text' name='vendedor' id='vendedor' data-id="" data-url="{!! route('sellers.index') !!}"/>
                </div>
                <div class='form-group'>
                    <label for='name'>Fecha</label>
                    <input class='form-control' type='text' name='date' id='date'/>
                </div>
                <div class='form-group'>
                    <label for='name'>Valor neto</label>
                    <input class='form-control' type='text' name='value_neto' id='value_neto'/>
                </div>
                <div class='form-group'>
                    <label for='name'>Observacion visita</label>
                    <textarea cols="15" rows="10" name="observation_visit" class="form-control"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary visits insert" id="visit_submit">Guardar</button>
                </div>
                {!! Form::close() !!}
            </div>

        </div>
    </div>
</div>